services:
  gitness:
    image: harness/gitness
    container_name: gitness
    environment:
      - GITNESS_URL_BASE=http://${URL}
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always